set-option -g default-terminal "screen-256color"
set-option -g prefix C-a

# scrollback buffer n lines
set -g history-limit 50000

# tmux powerline config
set-option -g status on
set-option -g status-interval 2
set-option -g status-utf8 on
set-option -g status-justify "centre"
set-option -g status-left-length 60
set-option -g status-right-length 90
source ~/.local/lib/python2.7/site-packages/powerline/bindings/tmux/powerline.conf

