#!/bin/bash

reset
sudo apt update && sudo apt dist-upgrade -y && \
sudo apt install -y \
  autojump \
  bat \
  blender \
  build-essential \
  chromium-browser \
  cmus \
  digikam \
  default-jre \
  eza \
  ffmpegthumbs \
  firefox \
  firefox-locale-es \
  filelight \
  fdupes \
  fd-find \
  findimagedupes \
  flatpak \
  gawk \
  git \
  git-delta \
  htop \
  intel-gpu-tools \
  jq \
  kde-config-tablet \
  krita \
  kcolorchooser \
  kdenlive \
  kruler \
  kubuntu-restricted-addons \
  meld \
  mediainfo \
  mesa-utils \
  mkvtoolnix-gui \
  mpv \
  net-tools \
  nvtop \
  language-pack-en \
  language-pack-es \
  language-pack-kde-es \
  language-pack-kde-en \
  libnotify-bin \
  libreoffice \
  libreoffice-kf5 \
  libreoffice-plasma \
  libreoffice-qt5 \
  libreoffice-l10n-es \
  libreoffice-l10n-en-gb \
  lm-sensors \
  obs-studio \
  offlineimap \
  okteta \
  okular-extra-backends \
  pandoc \
  partitionmanager \
  powertop \
  python3-pip \
  pulseeffects \
  silversearcher-ag \
  sshpass \
  sqlite3 \
  sweeper \
  tldr \
  translate-shell \
  tree \
  unrar \
  vainfo \
  vim-nox \
  vlc \
  watchman \
  wget \
  whois \
  xclip \
  xsel \
  xournalpp \
  zstd
  #deborphan

sudo apt update && sudo apt dist-upgrade -y

sudo snap install \
  telegram-desktop \
  glaxnimate \
  pixelorama \
  dbeaver-ce \
  jdownloader2

sudo snap install --classic obsidian

# virtualbox stuff
#ACCEPT_EULA=Y sudo apt install -y \
#  virtualbox \
#  virtualbox-ext-pack \
#  virtualbox-guest-utils \
#  virtualbox-qt \
