#!/bin/bash

reset
sudo apt update && sudo apt dist-upgrade -y && \
sudo apt install -y \
  aptitude \
  autojump \
  bat \
  blender \
  build-essential \
  chromium-browser \
  cmus \
  digikam \
  deborphan \
  default-jre \
  ffmpegthumbs \
  firefox \
  firefox-locale-es \
  filelight \
  fdupes \
  fd-find \
  findimagedupes \
  gawk \
  git \
  htop \
  intel-gpu-tools \
  jq \
  kalendar \
  kde-config-tablet \
  krita \
  kcolorchooser \
  kdenlive \
  kruler \
  kubuntu-restricted-addons \
  meld \
  mediainfo \
  mesa-utils \
  mkvtoolnix-gui \
  mpv \
  net-tools \
  language-pack-en \
  language-pack-es \
  language-pack-kde-es \
  language-pack-kde-en \
  libnotify-bin \
  lm-sensors \
  okteta \
  pandoc \
  partitionmanager \
  plasma-applet-redshift-control \
  powertop \
  pulseeffects \
  redshift \
  silversearcher-ag \
  sshpass \
  sqlite3 \
  sweeper \
  tldr \
  translate-shell \
  tree \
  unclutter \
  unrar \
  vlc \
  wget \
  whois \
  xclip \
  xsel \
  zstd

sudo aptitude update && sudo aptitude dist-upgrade
check-language-support | xargs sudo aptitude install -y

sudo snap install telegram-desktop

# virtualbox stuff
ACCEPT_EULA=Y sudo apt install -y \
  virtualbox \
  virtualbox-ext-pack \
  virtualbox-guest-utils \
  virtualbox-qt \
