#!/bin/bash

echo "Install asdf version manager ..."

asdf_version="0.13.1"
asdf_install_dir="$HOME/.local/share/asdf"

if [ ! -d "$asdf_install_dir" ]; then
  echo "> installing asdf ..."
  git clone https://github.com/asdf-vm/asdf.git $asdf_install_dir --branch v$asdf_version
  . $asdf_install_dir/asdf.sh
  asdf plugin list all
else
  echo "> upgrading asdf ..."
  cd $asdf_install_dir
  git fetch -p; git checkout v$asdf_version
  cd -
  asdf plugin update --all
fi

asdf plugin add ruby
asdf plugin add python
asdf plugin add nodejs
asdf plugin add elixir
asdf plugin add erlang
asdf plugin add cmake
asdf plugin add crystal
asdf plugin add rust

# install dependencies for compile runtimes
sudo aptitude install -y \
  automake \
  autoconf \
  xsltproc \
  unixodbc-dev \
  inotify-tools \
  libwxbase3.2-1 \
  libwxgtk-webview3.2-dev \
  fop \
  build-essential \
  libssl-dev \
  zlib1g-dev \
  libbz2-dev \
  libevent-dev \
  libreadline-dev \
  libsqlite3-dev \
  libpcre2-dev \
  libpq-dev \
  libyaml-dev \
  wget \
  curl \
  llvm \
  libncurses-dev \
  xz-utils \
  tk-dev \
  libffi-dev \
  liblzma-dev \
  git

asdf install ruby 3.2.2
asdf install python 3.11.6
asdf install nodejs 20.0.0
asdf install cmake 3.26.3
asdf install crystal 1.10.1
