#!/bin/bash

echo "Install asdf version manager ..."

asdf_version="0.11.3"
asdf_install_dir="$HOME/.local/share/asdf"

if [ ! -d "$asdf_install_dir" ]; then
  echo "> installing asdf ..."
  git clone https://github.com/asdf-vm/asdf.git $asdf_install_dir --branch v$asdf_version
  . $asdf_install_dir/asdf.sh
  asdf plugin list all
else
  echo "> upgrading asdf ..."
  cd $asdf_install_dir
  git fetch -p; git checkout $asdf_version
  cd -
  asdf plugin update --all
fi

asdf plugin add ruby
asdf plugin add python
asdf plugin add nodejs
asdf plugin add elixir
asdf plugin add erlang

# install dependencies for compile runtimes
sudo aptitude install -y \
  automake \
  autoconf \
  xsltproc \
  unixodbc-dev \
  libwxbase3.0-0v5 \
  libwxbase3.0-dev \
  fop \
  build-essential \
  libssl-dev \
  zlib1g-dev \
  libbz2-dev \
  libreadline-dev \
  libsqlite3-dev \
  libpq-dev \
  wget \
  curl \
  llvm \
  libncurses5-dev \
  libncursesw5-dev \
  xz-utils \
  tk-dev \
  libffi-dev \
  liblzma-dev \
  git

asdf install ruby 3.2.1
asdf install python 3.11.3
asdf install nodejs 20.0.0
