#!/bin/bash

# install vim and C++ LSP server
sudo aptitude install -y \
    aspell \
    aspell-en \
    aspell-es \
    vim-nox \
    exuberant-ctags \
    clangd-12 \
    clang-format \
    python3 \
    python3-pip

# install python deps
pip install --upgrade \
    'python-lsp-server<=1.3.3' \
    'jedi<0.18.0' \
    'flake8>=3.9.2,<4' \
    rope \
    mccabe \
    'pycodestyle<2.8.0,>=2.7.0' \
    pydocstyle \
    'autopep8<1.6.0' \
    pyls-mypy \
    pyls-isort \
    python-lsp-black \
    python-language-server[all] \
    pylint \
    pylint_django \
    pynvim

if command -v vim >/dev/null 2>&1; then
    echo "Bootstraping Vim"
    vim -es '+PlugUpdate' '+PlugClean' '+qal' || true
fi
