#!/bin/bash

# install vim and C++ LSP server
sudo apt install -y \
    aspell \
    aspell-en \
    aspell-es \
    vim-nox \
    exuberant-ctags \
    clangd-14 \
    clang-format \
    python3 \
    python3-pip

# install python deps
pip install --upgrade pynvim

if command -v vim >/dev/null 2>&1; then
    echo "Bootstraping Vim"
    vim -es '+PlugUpdate' '+PlugClean' '+qal' || true
    mkdir -p ~/.vim/undodir
fi
