#!/bin/bash

pyenv_version=v2.2.0
pyenv_repo=git://github.com/pyenv/pyenv.git
pyenv_install_path=$HOME/.pyenv

# install dependencies
sudo aptitude install -y \
  build-essential \
  libssl-dev \
  zlib1g-dev \
  libbz2-dev \
  libreadline-dev \
  libsqlite3-dev \
  wget \
  curl \
  llvm \
  libncurses5-dev \
  libncursesw5-dev \
  xz-utils \
  tk-dev \
  libffi-dev \
  liblzma-dev \
  python-openssl \
  git


if [ -d "$pyenv_install_path" ]; then
  cd ${pyenv_install_path} && git fetch -p && git checkout $pyenv_version && cd -
else
  git clone $pyenv_repo -o $pyenv_install_path -b $pyenv_version
fi
