#!/bin/bash

rbenv_version=v1.2.0
rbenv_repo=git://github.com/rbenv/rbenv.git
rbenv_install_path=$HOME/.rbenv

# install dependencies
sudo aptitude install -y \
  build-essential \
  libssl-dev \
  zlib1g-dev \
  libbz2-dev \
  libreadline-dev \
  libsqlite3-dev \
  wget \
  curl \
  llvm \
  libncurses5-dev \
  libncursesw5-dev \
  xz-utils \
  tk-dev \
  libffi-dev \
  liblzma-dev \
  git


if [ -d "$rbenv_install_path" ]; then
  cd ${rbenv_install_path} && git fetch -p && git checkout $rbenv_version && cd -
else
  git clone $rbenv_repo $rbenv_install_path -b $rbenv_version
fi
