#!/bin/bash

rbenv_version=v1.2.0
rbenv_repo=https://github.com/rbenv/rbenv.git
rbenv_install_path=$HOME/.rbenv
rbenv_build_version=v20220610

# install dependencies
sudo aptitude install -y \
  build-essential \
  libssl-dev \
  zlib1g-dev \
  libbz2-dev \
  libreadline-dev \
  libsqlite3-dev \
  wget \
  curl \
  llvm \
  libncurses5-dev \
  libncursesw5-dev \
  xz-utils \
  tk-dev \
  libffi-dev \
  liblzma-dev \
  git


if [ -d "$rbenv_install_path" ]; then
  rbenv update
else
  git clone $rbenv_repo $rbenv_install_path -b $rbenv_version

  # install plugins
  mkdir -p ${rbenv_install_path}/plugins

  # ruby-build
  cd ${rbenv_install_path}/plugins && git clone https://github.com/rbenv/ruby-build.git -b $rbenv_build_version
  # rbenv-default-gems
  cd ${rbenv_install_path}/plugins && git clone https://github.com/rbenv/rbenv-default-gems.git
  echo "bundler\nrake\nsolargraph" > ${rbenv_install_path}/default-gems
  # rbenv-update
  cd ${rbenv_install_path}/plugins && git clone https://github.com/rkh/rbenv-update.git
fi
