#!/bin/bash

echo "Bootstraping zsh"

sudo apt install -y \
  zsh \
  tmux


# ------
# --- Install ohmyzsh
# ------


echo "Bootstraping oh my zsh"

ohmyzsh_repo='https://github.com/robbyrussell/oh-my-zsh.git'
ohmyzsh_install_path=${HOME}/.oh-my-zsh

if [ ! -d "$ohmyzsh_install_path" ]; then
  git clone $ohmyzsh_repo $ohmyzsh_install_path
  mkdir -p ${ohmyzsh_install_path}/custom/themes
  ln -s ${XDG_CONFIG_HOME:-$HOME/.config}/yadm/robbyrussell.zsh-theme ${ohmyzsh_install_path}/custom/themes/robbyrussell.zsh-theme
  chsh -s /usr/bin/zsh
fi

# ------
# --- Configure tmux
# ------


echo "Bootstraping tmux"

pip install --upgrade powerline-status psutil

tmux_tpm_install_path=~/.config/tmux/plugins/tpm

if [ -d "$tmux_tpm_install_path" ]; then
  cd $tmux_tpm_install_path && git fetch -p && git pr origin master && cd -
else
  mkdir -p ~/.config/tmux/plugins
  git clone https://github.com/tmux-plugins/tpm $tmux_tpm_install_path
fi
