#!/bin/bash

echo "Bootstraping docker"

# dependencies
sudo apt install -y \
     ca-certificates \
     curl \
     gnupg \
     lsb-release

if [ ! -f "/usr/share/keyrings/docker-archive-keyring.gpg" ]; then
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
fi

if [ ! -f "/etc/apt/sources.list.d/docker.list" ]; then
  echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
    $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
fi

sudo apt update && sudo apt install -y docker-ce docker-ce-cli  containerd.io docker-compose-plugin

# add current user to docker
u=$USER
sudo usermod -aG docker $u
