#!/bin/bash

echo "Bootstrap CMake"

sign_key_filename=/usr/share/keyrings/kitware-archive-keyring.gpg
repository_file=/etc/apt/sources.list.d/kitware.list

wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | \
  gpg --dearmor - | sudo tee $sign_key_filename >/dev/null

if [ ! -f "$repository_file" ]; then
  echo "deb [signed-by=$sign_key_filename] https://apt.kitware.com/ubuntu/ $(lsb_release -cs) main" | \
    sudo tee $repository_file >/dev/null

  sudo apt update
  sudo rm -f $sign_key_filename

  sudo apt install -y kitware-archive-keyring cmake cmake-qt-gui
else
  sudo rm -f $sign_key_filename
fi
