#!/bin/bash

echo "Bootstrap Keybase"

repository_file=/etc/apt/sources.list.d/keybase.list

if [ ! -f "$repository_file" ]; then
  curl --remote-name https://prerelease.keybase.io/keybase_amd64.deb --output /tmp/keybase_amd64.deb
  sudo apt install /tmp/keybase_amd64.deb
fi
