#!/bin/bash

echo "Bootstrap Syncthing"

syncthing_running=$(docker inspect --format="{{.State.Running}}" syncthing 2> /dev/null)
syncthing_conf_file=~/.config/syncthing.conf
syncthing_dir=~/.local/share/syncthing

if [ ! -f "$syncthing_conf_file" ]; then
  echo "HOST=$(hostname)" > $syncthing_conf_file
  echo "VOLUME_MOUNT=$HOME/.local/share/syncthing/" >> $syncthing_conf_file
  echo "PRIVATE_NET_ADDR=127.0.0.1" >> $syncthing_conf_file
fi

if [ "$syncthing_running" == "false" ]; then
  docker compose -f $syncthing_dir/docker-compose.yml --env-file $syncthing_conf_file up -d
fi

# special settings for chromium
apparmor_chromium_conf=/etc/apparmor.d/tunables/home.d/chromium

if [ ! -f $apparmor_chromium_conf ]; then
  sudo echo "@{HOMEDIRS}+=$HOME/.local/share/syncthing" > $apparmor_chromium_conf
  sudo rm -f /etc/apparmor.d/cache/* /var/cache/apparmor/snap.*
fi

# install syncthing tray
syncthing_tray_version=1.2.2
syncthing_tray_bin=syncthingtray-$syncthing_tray_version-x86_64-pc-linux-gnu
syncthing_tray_bin_path=$HOME/.local/bin/$syncthing_tray_bin
syncthing_tray_url=https://github.com/Martchus/syncthingtray/releases/download/v$syncthing_tray_version/$syncthing_tray_bin.tar.xz

if [ ! -f $syncthing_tray_bin_path ]; then
  # remove previous versions if any
  rm -f ~/.local/bin/syncthingtray*
  curl -L $syncthing_tray_url --output /tmp/$syncthing_tray_bin.tar.xz
  tar -Jxvf /tmp/$syncthing_tray_bin.tar.xz --directory=$HOME/.local/bin/
  ln -s ~/.local/bin/syncthingtray-x86_64-pc-linux-gnu ~/.local/bin/syncthingtray
fi

# create symlinks
documents_dir="$HOME/Documents"

for link in Courses Invoices Other\ docs Payrolls Renta\ Moises Secrets Wiki Work\ documents; do
  if [ ! -L "$documents_dir/$link" ]; then
    ln -s "$syncthing_dir/$link" "$documents_dir/$link"
  fi
done

for link in Downloads Pictures; do
  if [ ! -L "$HOME/$link" ]; then
    if [ -d "$HOME/$link" ]; then
      mv "$HOME/$link" "$HOME/$link.old"
    fi

    ln -s "$syncthing_dir/$link" "$HOME/$link"
  fi
done
