#!/bin/bash

echo "Bootstrap OBS Studio"


repository_file="/etc/apt/sources.list.d/obsproject-ubuntu-obs-studio-$(lsb_release -cs).list"

if [ ! -f "$repository_file" ]; then
  sudo add-apt-repository ppa:obsproject/obs-studio
  sudo aptitude update && sudo aptitude -y \
    ffmpeg \
    v4l2loopback-dkms \
    obs-studio
fi
