#!/bin/bash

echo "Bootstrap Xournal++"

repository_file="/etc/apt/sources.list.d/apandada1-ubuntu-xournalpp-stable-$(lsb_release -cs).list"

if [ ! -f "$repository_file" ]; then
  sudo apt install -y software-properties-common

  sudo add-apt-repository -y ppa:apandada1/xournalpp-stable
  sudo apt update && sudo apt install -y \
    xournalpp
fi
