#!/bin/bash

echo "Bootstrap ugee m708 pentablet"

ugee_file="/usr/lib/ugee-pentablet/ugee-pentablet"
driver_url=https://ugeecom-download.oss-us-west-1.aliyuncs.com/file/2022/02/UGEE-pentablet-3.2.3.220107-1.x86_64.deb

if [ ! -f "$ugee_file" ]; then
  curl $driver_url --output /tmp/ugee.deb
  sudo apt install /tmp/ugee.deb
fi
