#!/bin/bash


# install latest nvim from appimage
neovim_appimage_url=https://github.com/neovim/neovim/releases/download/stable/nvim.appimage
cd ~/.local/bin/
curl -LO $neovim_appimage_url
chmod +x nvim.appimage
cd -

if [ ! -f ~/.local/bin/nvim ]; then
  ln -s ~/.local/bin/nvim.appimage ~/.local/bin/nvim

  # set nvim as vim alternative
  sudo update-alternatives --install $(which vim) vim ~/.local/bin/nvim 10
  sudo update-alternatives --set vim ~/.local/bin/nvim
fi

# install providers
pip install --upgrade \
  pynvim \
  proselint \
  openai


# LSP servers for python and ruby are installed using pyenv and rbenv

# install LSP deps for C++ and dictionaries
sudo apt install -y \
    aspell \
    aspell-en \
    aspell-es \
    clangd-14 \
    clang-format \
    clang-tools \
    clang-tidy

# install LSP server for HTML
npm install -g \
  vscode-langservers-extracted \
  livedown \
  prettier \
  remark-cli \
  remark-toc \
  remark-preset-lint-consistent \
  remark-preset-lint-recommended

# install elixir-ls
elixir_ls_version=0.17.10
elixir_ls_dir=~/.local/share/elixir-ls/
elixir_ls_release="https://github.com/elixir-lsp/elixir-ls/releases/download/v${elixir_ls_version}/elixir-ls-v${elixir_ls_version}.zip"

cd /tmp
curl -LO $elixir_ls_release
unzip elixir-ls-v${elixir_ls_version}.zip -d elixir-ls
mkdir -p $elixir_ls_dir
rm -rf ${elixir_ls_dir}/*
cp -R ./elixir-ls/* $elixir_ls_dir
cd -


# install crysalline lsp
crystalline_version=0.11.0
crystalline_file=~/.local/bin/crystalline
crystalline_release="https://github.com/elbywan/crystalline/releases/download/v${crystalline_version}/crystalline_x86_64-unknown-linux-musl.gz"

cd /tmp
curl -LO $crystalline_release
gunzip crystalline_x86_64-unknown-linux-musl.gz
cp crystalline_x86_64-unknown-linux-musl $crystalline_file
cd -
