#!/bin/bash

# set nvim as vim alternative
sudo update-alternatives --install /usr/bin/vim vim $ASDF_DATA_DIR/shims/nvim 10
sudo update-alternatives --set vim $ASDF_DATA_DIR/shims/nvim

# LSP servers for python and ruby are installed using pyenv and rbenv

# install LSP deps for C++ and dictionaries
sudo apt install -y \
    aspell \
    aspell-en \
    aspell-es \
    clangd-14 \
    clang-format \
    clang-tools \
    clang-tidy


# install crysalline lsp
crystalline_version=0.13.1
crystalline_file=~/.local/bin/crystalline
crystalline_release="https://github.com/elbywan/crystalline/releases/download/v${crystalline_version}/crystalline_x86_64-unknown-linux-musl.gz"

cd /tmp
curl -LO $crystalline_release
gunzip crystalline_x86_64-unknown-linux-musl.gz
cp crystalline_x86_64-unknown-linux-musl $crystalline_file
cd -
