---
services:
  syncthing:
    image: syncthing/syncthing:1.27.12
    container_name: syncthing
    hostname: ${HOST}
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${VOLUME_MOUNT}:/var/syncthing
    ports:
      - ${PRIVATE_NET_ADDR}:8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
    mem_limit: 512M
    cpu_count: 2
    restart: unless-stopped
